// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/gofiber/fiber/v3"
	"github.com/google/wire"
	"github.com/rakhiazfa/fiber-boilerplate/internal/database"
	"github.com/rakhiazfa/fiber-boilerplate/internal/delivery/http/handler"
	"github.com/rakhiazfa/fiber-boilerplate/internal/delivery/http/router"
	"github.com/rakhiazfa/fiber-boilerplate/internal/service"
)

// Injectors from wire.go:

func NewApplication() *fiber.App {
	errorHandler := handler.NewErrorHandler()
	db := database.NewPostgreSQLConnection()
	healthcheckService := service.NewHealthcheckService(db)
	healthcheckHandler := handler.NewHealthcheckHandler(healthcheckService)
	healthcheckRouter := router.NewHealthcheckRouter(healthcheckHandler)
	app := router.New(errorHandler, healthcheckRouter)
	return app
}

// wire.go:

var healthcheckModule = wire.NewSet(service.NewHealthcheckService, handler.NewHealthcheckHandler, router.NewHealthcheckRouter)
