// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/gofiber/fiber/v3"
	"github.com/google/wire"
	"github.com/rakhiazfa/fiber-boilerplate/internal/database"
	"github.com/rakhiazfa/fiber-boilerplate/internal/delivery/http/handler"
	"github.com/rakhiazfa/fiber-boilerplate/internal/delivery/http/router"
	"github.com/rakhiazfa/fiber-boilerplate/internal/service"
)

// Injectors from wire.go:

func NewApplication() *fiber.App {
	errorHandler := handler.NewErrorHandler()
	db := database.NewPostgreSQLConnection()
	healthCheckService := service.NewHealthCheckService(db)
	healthCheckHandler := handler.NewHealthCheckHandler(healthCheckService)
	healthCheckRouter := router.NewHealthCheckRouter(healthCheckHandler)
	app := router.New(errorHandler, healthCheckRouter)
	return app
}

// wire.go:

var healthCheckModule = wire.NewSet(service.NewHealthCheckService, handler.NewHealthCheckHandler, router.NewHealthCheckRouter)
