// Code generated by kessoku. DO NOT EDIT.

package bootstrap

import (
	"github.com/mazrean/kessoku"
	"github.com/rakhiazfa/fiber-boilerplate/internal/bootstrap/application"
	"github.com/rakhiazfa/fiber-boilerplate/internal/bootstrap/database"
	"github.com/rakhiazfa/fiber-boilerplate/internal/bootstrap/logger"
	"github.com/rakhiazfa/fiber-boilerplate/internal/delivery/http/handler"
	"github.com/rakhiazfa/fiber-boilerplate/internal/delivery/http/router"
	"github.com/rakhiazfa/fiber-boilerplate/internal/service"
)

func Init() *application.Application {
	logger0 := kessoku.Provide(logger.New).Fn()()
	db := kessoku.Provide(database.NewPostgreSQLConnection).Fn()(logger0)
	errorHandler := kessoku.Provide(handler.NewErrorHandler).Fn()(logger0)
	healthCheckService := kessoku.Provide(service.NewHealthCheckService).Fn()(db)
	healthCheckHandler := kessoku.Provide(handler.NewHealthCheckHandler).Fn()(healthCheckService)
	healthCheckRouter := kessoku.Provide(router.NewHealthCheckRouter).Fn()(healthCheckHandler)
	application0 := kessoku.Provide(application.New).Fn()(logger0, db, errorHandler, healthCheckRouter)
	return application0
}
